#!/bin/bash

# Copyright (c) 2016, Stefan Heitmüller <stefan.heitmueller@gmx.com>

# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

if [[ -w /dev/zfs ]]; then
    __ZFS_CMD="zfs"
    __ZNAPZENDZETUP_CMD="znapzendzetup"
else
    __ZFS_CMD="sudo zfs"
    __ZNAPZENDZETUP_CMD="sudo znapzendzetup"
fi

__znapzendzetup_get_commands()
{
    $__ZNAPZENDZETUP_CMD | awk '/^\s{8}[a-z]/ {print $1}' | cut -f1 -d '|' | uniq | sort
}

__znapzendzetup_list_datasets()
{
    $__ZNAPZENDZETUP_CMD list 2>&1 | grep -E '^*** backup plan: .* ***$' | awk '{print $(NF-1)}' | uniq | sort
}

__zfs_list_datasets()
{
    $__ZFS_CMD list -H -o name -t filesystem,volume
}

__znapzendzetup_complete()
{
    local cur prev cmd cmds
    COMPREPLY=()
    # Don't split on colon
    _get_comp_words_by_ref -n : -c cur -p prev -w COMP_WORDS -i COMP_CWORD
    cmd="${COMP_WORDS[1]}"

    if [[ ${prev##*/} == znapzendzetup ]]
    then
        cmds=$(__znapzendzetup_get_commands)
        COMPREPLY=($(compgen -W "$cmds -?" -- "$cur"))
        return 0
    fi

    case "${cmd}" in
        create|delete|edit|enable|disable|export|list)
                COMPREPLY=($(compgen -W "$(__znapzendzetup_list_datasets)" -- "$cur"))
        ;;
        import)
		COMPREPLY=($(compgen -W "$(__zfs_list_datasets)" -- "$cur"))
        ;;
    esac

    __ltrim_colon_completions "$cur"
    return 0
}

complete -F __znapzendzetup_complete znapzendzetup
