=head1 NAME

znapzendzetup - znapzend setup utility

=head1 SYNOPSIS

B<znapzendzetup> I<command> [I<options...>]

where 'command' is one of the following:

    create [--recursive] [--mbuffer=<path>] [--mbuffersize=<size>] \
           [--tsformat=<format>] --donotask \
           SRC plan dataset \
           [ DST[:key] plan [[user@]host:]dataset ]

    delete [--dst=key] <src_dataset>

    edit [--recursive=on|off] [--mbuffer=<path>|off] [--mbuffersize=<size>] \
           [--tsformat=<format>] --donotask \
           SRC [plan] dataset \
           [ DST:key [plan] [dataset] ]

    enable <src_dataset>

    disable <src_dataset>

    list [src_dataset]

    help

    man

=head1 DESCRIPTION

Znapzend is a snapshot based zfs backup daemon creating snapshots on a
scheduled basis on the source filesystem and on a destination filesystem

=head2 Create Command

The heart of the znapzend backup is the plan. The plan specifies how often
to backup and for how long to keep the backups. A plan is required both for
the source and the destination datasets.

The plan consists of a series of retention periodes to interval
associations:

  retA=>intA,retB=>intB,...

Both intervals and retention periods are expressed in standard units of time
or multiples of them. You can use both the full name or a shortcut according
to the following table:

 second|sec|s
 minute|min|M
 hour|h
 day|d
 week|w
 mon|month|m
 year|y

To keep one copy every 30 minutes for one week, specify:
 
 1week=>30min

To keep one copy every two days for 10 years:

 10year=>2day


The 'tsformat' option specifies the format of the snapshots being created.
The syntax is 'strftime like'. The string must consist of the mandatory

 (%Y, %m, %d, %H, %M, %S)

and optional

 (-, _, ., :)

characters.

If not specified, tsformat defaults to '%Y-%m-%d-%H%M%S'.

If mbuffer is specified, the size of the mbuffer can be set with
the 'mbuffersize' option. mbuffersize supports the following units:

 b, k, M, G

To specify a mbuffer size of 100 MB:

 --mbuffersize=100M

If not set, mbuffersize defaults to 1 GB.

Use option 'donotask' for create/edit to run changes immediately.

=head1 EXAMPLE

    znapzendzetup create -r --mbuffer=/opt/omni/bin/mbuffer \
       --mbuffersize=1337M --tsformat='%Y-%m-%d-%H%M%S' \
       SRC '7d=>1h,30d=>4h,90d=>1d' tank/home \
       DST:a '7d=>1h,30d=>4h,90d=>1d,1y=>1w,10y=>1month' backup/home \
       DST:b '7d=>1h,30d=>4h,90d=>1d,1y=>1w,10y=>1month' root@bserv:backup/home

=head1 COPYRIGHT

Copyright (c) 2014 by OETIKER+PARTNER AG. All rights reserved.

=head1 LICENSE

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option)
any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see L<http://www.gnu.org/licenses/>.

=head1 AUTHOR

S<Tobias Oetiker E<lt>tobi@oetiker.chE<gt>>
S<Dominik Hassler>

=head1 HISTORY

2014-06-29 had Flexible snapshot time format
2014-06-01 had Multi destination backup
2014-05-30 had Initial Version

=cut

