=head1 NAME

znapzend - znapzend daemon

=head1 SYNOPSIS

B<znapzend.pl> [I<options>...]

 --man         show man-page and exit
 -h,--help     display this help and exit 
 -d,--debug    print debug messages to STDERR
 -n,--noaction run in simulation mode. does no changes to the filesystem
 --nodestroy   does all changes on the filesystem except destroy
 --syslog=x    select the syslog facility 
 --pidfile=x   write a pid file when running in daemon mode
 --daemonize   fork into the background

=head1 DESCRIPTION

znapzend is a snapshot based zfs backup daemon creating snapshots on a scheduled basis on the source filesystem and on a destination filesystem

=head1 COPYRIGHT

Copyright (c) 2014 by OETIKER+PARTNER AG. All rights reserved.

=head1 LICENSE

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option)
any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see L<http://www.gnu.org/licenses/>.

=head1 AUTHOR

S<Tobias Oetiker E<lt>tobi@oetiker.chE<gt>>
S<Dominik Hassler>

=head1 HISTORY

2014-06-01 had Multi destination backup
2014-05-30 had Initial Version

=cut

