#!/usr/bin/env perl

use strict;
use warnings;

#print zfs command
print STDERR '# ssh ' . join(' ', @ARGV) . "\n";

while (@ARGV){
    shift @ARGV && next if $ARGV[0] =~ /^-|=/;

    shift @ARGV;
    last;
}

system @ARGV;

1;

