name: Build Docker

on:
  push:
    branches-ignore:
    - master
    tags-ignore:
    - "*"
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
    # Allow manually running the action, e.g. if disabled after some quietness in the source

jobs:
  docker:
    name: Build and test in Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test within image
      run: docker build --target test .
