name: Run Tests

on:
  push:
    branches:
    - master
    tags-ignore:
    - "*"
  pull_request:
    
jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
        - "5.32"
        - "5.30"
        - "5.26"
        - "5.36"
#        - "5.22"
#        - "5.18"
#        - "5.10"
    name: Perl ${{ matrix.perl }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
    - run: ./bootstrap.sh
    - run: ./configure --prefix=$HOME/znapzend
    - run: make test-deps
    - run: ./test.sh
    - run: make install
    - run: "echo \"repo_token: ${{ secrets.GITHUB_TOKEN }}\" > .coveralls.yml"
    - run: perl -I./thirdparty/lib/perl5 thirdparty/bin/cover -report coveralls
